### ISSUE TITLE
Error Setup SteamOS

### ISSUE THREAD

**Issue by HinataNekoNya** [Bloxxel64/SM64LinuxLauncher-Legacy#11] opened 2023-10-13 20:10 UTC
Traceback (most recent call last):
  File "/home/deck/.SM64-Launcher/setup.py", line 5, in <module>
    from pip._internal import main as pip_main
ModuleNotFoundError: No module named 'pip'

**Comment by ezntek** [comment] 2023-10-14 12:49
duplicate of #8 

> try using my fork on this branch [here](https://github.com/ezntek/SM64LinuxLauncher/tree/fix-installer), i've fixed the bug.

you have to use my fork for now, or at least before my MR #9 is accepted.
Make sure you have pip installed. run the `pip` command. if it says command not found,  run `python3 -m ensurepip`, and be sure to let me know if it works or not.

**Comment by HinataNekoNya** [comment] 2023-10-15 11:19
it work

**Comment by HinataNekoNya** [comment] 2023-10-15 11:20
but y have another problem

**Comment by ezntek** [comment] 2023-10-15 11:56
do let me know!

be sure to let any maintainer like me know exactly what problems you're having at one time, as this just causes delays.

**Comment by ezntek** [comment] 2023-10-18 00:28
PR #9 was just merged, so you can now use the main branch. If there are no further concerns, please close the issue.

**Closed as completed** 2023-10-31 13:50 UTC
